server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: rococo-gateway

logging:
  file:
    path: ./logs/rococo-gateway
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    net.devh.boot.grpc: INFO
    org.springframework.boot.autoconfigure: INFO

rococo-user:
  client: grpc
rococo-artist:
  client: grpc
rococo-museum:
  client: grpc
rococo-geo:
  client: grpc

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
grpc:
  client:
    grpcUserdataClient:
      address: 'static://127.0.0.1:8072'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      netty:
        use-native-transports: false
    grpcArtistClient:
      address: 'static://127.0.0.1:8074'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      netty:
        use-native-transports: false
    grpcGeoClient:
      address: 'static://127.0.0.1:8076'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      netty:
        use-native-transports: false
    grpcMuseumClient:
      address: 'static://127.0.0.1:8078'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      netty:
        use-native-transports: false

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8080'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

grpc:
  client:
    grpcUserdataClient:
      address: 'static://userdata.rococo.dc:8072'
      negotiationType: PLAINTEXT
    grpcArtistClient:
      address: 'static://artist.rococo.dc:8074'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://geo.rococo.dc:8076'
      negotiationType: PLAINTEXT
    grpcMuseumClient:
      address: 'static://museum.rococo.dc:8078'
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8080'
---
spring:
  config:
    activate:
      on-profile: 'prod'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      uri: https://vault.qa.guru
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.rococo.dboyko.qa'

grpc:
  client:
    grpcUserdataClient:
      address: ${rococo-userdata.grpc.url}
      negotiationType: PLAINTEXT
    grpcArtistClient:
      address: ${rococo-artist.grpc.url}
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: ${rococo-geo.grpc.url}
      negotiationType: PLAINTEXT
    grpcMuseumClient:
      address: ${rococo-museum.grpc.url}
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'https://rococo.dboyko.qa'
rococo-gateway:
  base-uri: 'https://api.rococo.dboyko.qa'
---
spring:
  config:
    activate:
      on-profile: 'staging'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      uri: https://vault.qa.guru
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.rococ-stage.dboyko.qa'

grpc:
  client:
    grpcUserdataClient:
      address: ${rococo-userdata.grpc.url}
      negotiationType: PLAINTEXT
    grpcArtistClient:
      address: ${rococo-artist.grpc.url}
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: ${rococo-geo.grpc.url}
      negotiationType: PLAINTEXT
    grpcMuseumClient:
      address: ${rococo-museum.grpc.url}
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'https://rococo-stage.dboyko.qa'
rococo-gateway:
  base-uri: 'https://api.rococo-stage.dboyko.qa'
---
